apiVersion: v1
kind: PersistentVolume
metadata:
  name: logger-shared-pv
  labels:
    type: glusterfs
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: glusterfs-cluster
    path: log-volume