apiVersion: v1
kind: PersistentVolume
metadata:
  name: logger-local-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/log/cortx"
