apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logger-local-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: logger-local-pv
